#### 5.1. Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B. Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.

In [15]:
import numpy as np

In [18]:
a = np.array([1,2,3,4,5])
b = np.array([[1],[2],[3],[4],[4]])
print('a = ', a)
print('b = ', b)

a =  [1 2 3 4 5]
b =  [[1]
 [2]
 [3]
 [4]
 [4]]


In [21]:
print(a+b,'\n**\n',b-a,'\n**\n',a*b)

[[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]
 [5 6 7 8 9]] 
**
 [[ 0 -1 -2 -3 -4]
 [ 1  0 -1 -2 -3]
 [ 2  1  0 -1 -2]
 [ 3  2  1  0 -1]
 [ 3  2  1  0 -1]] 
**
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 4  8 12 16 20]]


In [53]:
e = np.identity(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


    [1. 0. 0. 0. 0.]       [5. 0. 0. 0. 0.]       [4. -1. -1. -1. -1.]
    [0. 1. 0. 0. 0.]       [0. 5. 0. 0. 0.]       [-1. 4. -1. -1. -1.]
    [0. 0. 1. 0. 0.] * 5 = [0. 0. 5. 0. 0.] - 1 = [-1. -1. 4. -1. -1.]
    [0. 0. 0. 1. 0.]       [0. 0. 0. 5. 0.]       [-1. -1. -1. 4. -1.]
    [0. 0. 0. 0. 1.]       [0. 0. 0. 0. 5.]       [-1. -1. -1. -1. 4.]

In [54]:
print(5*e-1)

[[ 4. -1. -1. -1. -1.]
 [-1.  4. -1. -1. -1.]
 [-1. -1.  4. -1. -1.]
 [-1. -1. -1.  4. -1.]
 [-1. -1. -1. -1.  4.]]


#### 5.2. Вычислите определитель:

    [1. 2. 3]
    [4. 0. 6]
    [7. 8. 9]

In [51]:
a = np.array([[1,2,3],[4,0,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


        [1 2 3]
    det [4 0 6] = 1(0*9 - 8*6) - 2(4*9 - 7*6) + 3(4*8 - 7*0) = -48 + 12 + 96 = 60
        [7 8 9]

In [49]:
print(np.linalg.det(a))


59.999999999999986


#### 5.3. 1. Вычислите матрицу, обратную данной:
    [1 2 3]      [-48  -6  32]         [-48   6  32]         [-48   6  12]                     [  -0.8   0.1     0.2]
    [4 0 6]  M = [ -6 -12  -6]  A(*) = [  6 -12   6]  A(T) = [  6 -12   6]  det = 60  A(-1) =  [   0.1  -0.2     0.1]
    [7 8 9]      [ 12  -6  -8]         [ 12   6  -8]         [ 32   6  -8]                     [ 0.5(3)  0.1 -0.1(3)]

In [56]:
a = np.array([[1,2,3],[4,0,6],[7,8,9]])
print(np.linalg.inv(a))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


#### 2. Приведите пример матрицы 4х4, ранг которой равен 1.


    [0 0 0 0]    [0 0 0 0]
    [0 0 0 0]    [0 0 1 0]
    [0 0 0 0]    [0 0 0 0]
    [0 0 1 0]    [0 0 0 0]

In [143]:
a = np.array([[0,0,0,0],[0,0,1,0],[0,0,0,0]])
b = np.array([[0,0,0,0],[0,0,1,0],[0,0,0,0]])
print(np.linalg.matrix_rank(a))
print(np.linalg.matrix_rank(b))

1
1


#### 5.4.Вычислите скалярное произведение двух векторов: (1, 5)  и  (2, 8)

(1 * 2) + (5 * 8) = 42

In [150]:
a = np.array([1,5])
b = np.array([2,8])
print(a,b)
print(np.inner(a,b))

[1 5] [2 8]
42


#### 5.5 Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


In [153]:
a = np.array([1,5,0], float)
b = np.array([2,8,7], float)
c = np.array([7,1.5,3], float)
print(a,b,c)

[1. 5. 0.] [2. 8. 7.] [7.  1.5 3. ]


In [155]:
res1 = np.cross(a,b)
res2 = np.cross(b,c)
print(np.inner(res1,c))
print(np.inner(res2,a))

228.5
228.5
