#### 6.1 Решите линейную систему:

    [ 1 2 3 ]       [ 12 ]
    [ 4 0 6 ] * X = [  2 ]
    [ 7 8 9 ]       [  1 ]

In [16]:
import numpy as np

In [17]:
a = np.array([[1,2,3],[4,0,6],[7,8,9]])
b = np.array([[12],[2],[1]])
print(a)
print(b)

[[1 2 3]
 [4 0 6]
 [7 8 9]]
[[12]
 [ 2]
 [ 1]]


In [18]:
np.linalg.solve(a,b)

array([[-9.2       ],
       [ 0.9       ],
       [ 6.46666667]])

In [20]:
if np.linalg.det(a):
    a1 = np.linalg.inv(a)
    print(np.dot(a1,b))

[[-9.2       ]
 [ 0.9       ]
 [ 6.46666667]]


#### 2. Найдите псевдорешение:
x + 2y – z = 1

3x – 4y = 7

8x – 5y + 2z = 12

2x – 5z = 7

11x +4y – 7z = 15