### Теория вероятностей и математическая статистика. Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

#### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

#### zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
#### ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
#### Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy. Полученные значения должны быть равны. Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [1]:
import numpy as np

In [4]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [6]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [9]:
cov_ = (zp * ks).mean() - zp.mean() * ks.mean()
cov_

9157.839999999997

In [10]:
r = cov_ / (zp.std() * ks.std())
r

0.8874900920739158

In [14]:
cov2_ = np.sum((zp - zp.mean())*(ks - ks.mean()))/10
cov2_

9157.84

In [15]:
import pandas as pd

In [18]:
df = pd.DataFrame({ 'zp': zp, 'ks': ks }, columns=['zp', 'ks'])
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [21]:
df.corr().loc['zp','ks']

0.8874900920739162

#### 2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:
#### 131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
#### Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [23]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [24]:
varriance = iq.var(ddof=1)
varriance

111.21111111111111

In [47]:
s = varriance**0.5
s

10.54566788359614

In [48]:
t_kr = 2.26

In [53]:
m = iq.mean()
m

118.1

In [54]:
lim1 = m + t_kr * ( s / 10 ** 0.5)

In [55]:
lim2 = m - t_kr * ( s / 10 ** 0.5)

In [61]:
print("Доверительный интервал: {} - {}".format(round(lim2,3), round(lim1, 3)))

Доверительный интервал: 110.563 - 125.637


#### 3. Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [62]:
m = 174.2
s = 5
n = 27
t_kr = 2.06

In [64]:
lim1 = m + t_kr * ( s / 27 ** 0.5)
lim2 = m - t_kr * ( s / 27 ** 0.5)

In [65]:
print("Доверительный интервал: {} - {}".format(round(lim2,3), round(lim1, 3)))

Доверительный интервал: 172.218 - 176.182
