#### 6.1 Решите линейную систему:

    [ 1 2 3 ]       [ 12 ]
    [ 4 0 6 ] * X = [  2 ]
    [ 7 8 9 ]       [  1 ]

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,0,6],[7,8,9]])
b = np.array([[12],[2],[1]])
print(a)
print(b)

[[1 2 3]
 [4 0 6]
 [7 8 9]]
[[12]
 [ 2]
 [ 1]]


In [70]:
np.linalg.solve(a,b)

array([[-9.2       ],
       [ 0.9       ],
       [ 6.46666667]])

In [71]:
if np.linalg.det(a) > 0.0001:
    a1 = np.linalg.inv(a)
    print(np.dot(a1,b))

[[-9.2       ]
 [ 0.9       ]
 [ 6.46666667]]


#### 2. Найдите псевдорешение:
x + 2y – z = 1

3x – 4y = 7

8x – 5y + 2z = 12

2x – 5z = 7

11x +4y – 7z = 15

In [170]:
A = np.array([[1,2,-1],[3,-4,0],[8,-5,2],[2,0,-5],[11,4,-7]])
B = np.array([1,7,12,7,15])
np.linalg.lstsq(A,B)

/home/yura/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

#### 3. Сколько решений имеет линейная система:

    [1,2,3]       [12]
    [4,5,6] * X = [ 2]
    [7,8,9]       [ 1]

In [21]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([12,2,1])

In [22]:
np.linalg.solve(A,B)

array([-4.05323966e+16,  8.10647933e+16, -4.05323966e+16])

In [23]:
np.linalg.matrix_rank(A, 0.0001)

2

In [25]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[12,2,1]])
C = np.concatenate((A,B.T), axis=1)
print(C)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


In [26]:
np.linalg.matrix_rank(A,0.0001), np.linalg.matrix_rank(C,0.0001)

(2, 3)

Система не имеет решений.

In [161]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[4,5,6]])
np.linalg.matrix_rank(A,0.0001)

2

In [162]:
C = np.concatenate((A,B.T), axis=1)
np.linalg.matrix_rank(A,0.0001), np.linalg.matrix_rank(C,0.0001)

(2, 2)

In [163]:
B = B[0]
np.linalg.solve(A,B)

array([-7.33333333, 11.66666667, -4.        ])

#### 4. Вычислите LU-разложение матрицы:

    [1, 2, 3]
    [2,16,21]
    [4,28,73]

In [91]:
import scipy
import scipy.linalg

In [92]:
A = np.array([[1,2,3],[2,16,21],[4,28,73]])
P, L, U = scipy.linalg.lu(A)

In [93]:
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [94]:
print(np.dot(P,A) - np.dot(L,U))

[[ -2. -12. -52.]
 [  3.  26.  70.]
 [ -1. -14. -18.]]


#### 5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1

8x – 5y + 2z = 12

Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 

In [107]:
A = np.array([[1,2,-1],[8,-5,2]])
B = np.array([1,12])

In [108]:
np.linalg.lstsq(A,B)

/home/yura/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

#### 6. Найдите одно из псевдорешений вырожденной системы:

    [1,2,3]       [ 2]
    [4,5,6] * X = [ 5]
    [7,8,9]       [11]

Попробуйте также отыскать и нормальное псевдорешение.


In [105]:
A = np.array([[11,2,3],[4,15,6],[7,8,9]])
B = np.array([2,5,11])

In [106]:
np.linalg.lstsq(A,B)

/home/yura/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([-0.212     , -0.256     ,  1.61466667]),
 array([], dtype=float64),
 3,
 array([22.38542072,  9.57310515,  3.49979957]))